name: react CI/CD

on:
  push:
    branches:
      - feature4
      - feature5

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: npm install

      - name: Build the React App
        run: npm run build

      - name: List Dist Directory Contents
        run: ls -la dist

      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: List S3 Bucket Contents
        run: aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }} --recursive
